; (function () {
    //DEFINE BASE URL MODULES IF NOT GENERATED BY SERVER-SIDE
    if (!require.defined('baseurl')) {
        //DETERMINE BASE URL FROM CURRENT SCRIPT PATH
        var scripts = document.getElementsByTagName('script');
        var src = scripts[scripts.length - 1].src;
        var baseScriptsUrl = src.substring(src.indexOf(document.location.pathname), src.lastIndexOf('/'));

        //DEFINE BASE URL MODULES FOR RELATIVE PATHING LATER
        //TODO: OR !SIMPLY! CREATE JS MODULE SERVER-SIDE: HostingEnvironment.ApplicationVirtualPath
        define('baseurl', [], function () {
            //ASSUME SCRIPTS IS IN THE FOLLOWING FOLDERS
            var tempUrl = baseScriptsUrl.toLowerCase();
            var index = tempUrl.indexOf('/async');

            //CALCULATE VIRTUAL ROOT PATH BY SUBTRACTING CURRENT PATH
            return baseScriptsUrl.substring(0, index + 1);
        });
        define('basescriptsurl', [], function () { return baseScriptsUrl; });
        define('baseservicesurl', [], function () { return '~/api'; });
        define('basemvcurl', [], function () { return '~/mvcroute'; });
    }

    //HANDLE JQUERY IF LOADED ALREADY TO AVOID OVERWRITING EXISTING JQUERY PROPERTIES AND PLUGINS
    if (!window.jQuery) {
        //SPECIFY ALIAS TO PATH IN CONFIG
        require.config({
            paths: {
                jquery: 'libs/jquery/js/jquery.min'
            }
        });
    } else {
        //REGISTER THE CURRENT JQUERY
        define('jquery', [], function () { return window.jQuery; });
    }

    //CONFIFURE SHORTCUT ALIASES
    require.config({
        baseUrl: baseScriptsUrl,
        paths: {
            amplify: 'libs/amplify/js/amplify.min',
            blockui: 'libs/blockui/js/jquery.blockUI',
            bootstrap: 'libs/bootstrap/js/bootstrap.min',
            bootstrap3: 'libs/bootstrap/v3/js/bootstrap.min',
            bxslider: 'libs/bxslider/js/jquery.bxslider.min',
            cookie: 'libs/jquery-cookie/js/jquery-cookie',
            equalize: 'libs/equalize/js/equalize.min',
			fullcalendar: 'libs/fullcalendar/js/fullcalendar.min',
            hijri: 'libs/hijricalendar/js/hijricalendar.mod',
            html5shiv: 'libs/html5shiv/js/html5shiv.min',
            imagefill: 'libs/imagefill/js/jquery-imagefill',
            innerfade: 'libs/innerfade/js/jquery.innerfade.min',
            jplayer: 'libs/jplayer/js/jquery.jplayer.min',
            jqparse: 'libs/parse/js/jquery.parse',
            jqplaceholder: 'libs/jquery-placeholder/js/jquery.placeholder',
            jqueryui: 'libs/jquery-ui/js/jquery-ui.min',
            jsurl: 'libs/js-url/js/js-url.min',
            kendoall: 'libs/kendoui/js/kendo.all.min',
            kendodataviz: 'libs/kendoui/js/kendo.dataviz.min',
            kendomobile: 'libs/kendoui/js/kendo.mobile.min',
            kendoweb: 'libs/kendoui/js/kendo.web.min',
            kendoui: 'libs/kendoui/js', //FOR AMD USE
            mediaelement: 'libs/mediaelement/js/mediaelement.min',
            mediaelementplayer: 'libs/mediaelement/js/mediaelementplayer.min',
            modernizr: 'libs/modernizr/js/modernizr.min',
            moment: 'libs/moment/js/moment.min',
            mustache: 'libs/mustache/js/mustache.min',
			nprogress: 'libs/nprogress/js/nprogress',
            parse: 'libs/parse/js/parse.min',
            photobox: 'libs/photobox/js/photobox.min',
            respond: 'libs/respond/js/respond.min',
            sitefinityapi: 'libs/sitefinity/js/api',
            lostorage: 'libs/lostorage/js/loStorage.min',
            taffy: 'libs/taffy/js/taffy-min',
            text: 'libs/require/js/text',
            tinysort: 'libs/tinysort/js/jquery.tinysort.min',
            toastr: 'libs/toastr/js/toastr.min',
            underscore: 'libs/underscore/js/underscore-min',
            'underscore.string': 'libs/underscore/js/underscore.string.min'
        },
        // The shim config allows us to configure dependencies for
        // scripts that do not call define() to register a module
        shim: {
            amplify: {
                exports: 'amplify'
            },
            blockui: ['jquery'],
            bootstrap: ['jquery'],
            bootstrap3: ['jquery'],
            bxslider: ['jquery'],
            equalize: ['jquery'],
            fullcalendar: ['jquery'],
            imagefill: ['jquery'],
            innerfade: ['jquery'],
            jqparse: ['jquery'],
			jqplaceholder: ['jquery'],
            jsurl: {
                deps: ['jquery'],
                exports: 'url'
            },
            kendoall: {
                deps: ['jquery'],
                exports: 'kendo'
            },
            kendodataviz: {
                deps: ['jquery'],
                exports: 'kendo'
            },
            kendomobile: {
                deps: ['jquery'],
                exports: 'kendo'
            },
            kendoweb: {
                deps: ['jquery'],
                exports: 'kendo'
            },
            modernizr: {
                exports: 'Modernizr'
            },
            moment: {
                deps: ['jquery'],
                exports: 'moment'
            },
            nprogress: ['jquery'],
            parse: {
                exports: 'Parse'
            },
            photobox: ['jquery'],
            taffy: {
                exports: 'TAFFY'
            },
            tinysort: ['jquery'],
            toastr: {
                deps: ['jquery'],
                exports: 'toastr'
            },
            underscore: {
                deps: ['underscore.string'],
                exports: '_',
                init: function (_s) {
                    //MERGE STRING PLUGIN TO UNDERSCORE NAMESPACE
                    _.mixin(_s.exports());
                    return _;
                }
            },
            'utils/plugins': ['jquery']
        }
    });
})();
